services:
  dev-nvidia:
    build:
        context: ../src
        dockerfile: ../pytorch_setup/dev.dockerfile # this is relative to the context defined above
        args:
          USER_ID: ${USER_ID}
          GROUP_ID: ${GROUP_ID}
    image: rif/pytorch:latest
    container_name: rif_pytorch
    network_mode: "host"           # access to host's network
    stdin_open: true               # docker run -i
    tty: true                      # docker run -t
    privileged: true               # Needed for /dev volume
    runtime: nvidia
    environment:      
      - DISPLAY=${DISPLAY}             # Pass the display for GUI
      - QT_X11_NO_MITSHM=1             # Needed by QT programs
      - XAUTHORITY=/tmp/.docker.xauth
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - TERM=xterm-256color            # Enable terminal colors
    volumes:
       - /tmp/.X11-unix:/tmp/.X11-unix:rw
       - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
       - ../src:/home/dev/workspace/src
       - ../data:/home/dev/data
       - /dev/shm:/dev/shm
       - /dev:/dev
